//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        public string AccountHolders { get; set; }
        public int AccountNumber { get; set; }
        public string EmailId { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> Balance { get; set; }
        public string AccountType { get; set; }
    }
}
